dbDriver=oracle.jdbc.driver.OracleDriver
dbConnString=jdbc:oracle:thin:@
####### INICIO - Desarrollo properties ##########
#server=10.204.166.55
#puerto=1521
#base=DBCPMAILD
#dbUser=SAS
#dbPassword=fr4s8#cv5j
#LocationDataFile=//home//usuarios//sfi//sfi525//Desarrollo//crediticioBatch//bajadaAMDOCSMensual//archivo//
####### FIN - Desarrollo properties ##########
####### INICIO - TEST properties ##########
server=10.204.166.47
puerto=1521
base=DBCPMAILC
dbUser=RC_EXP
dbPassword=sdkgh_sdk26
LocationDataFile=C://home/applcred/
#LocationDataFile=//home//usuarios//sfi//sfi525//Test//crediticioBatch//bajadaAMDOCSMensual//archivo//
####### FIN - TEST properties ##########

DatafileName=RC_RIESGO_CREDITICIO_FINAL
extensionFile=.CSV
